### ISSUE TITLE
Не срабатывает DataSource при CollectionView.reloadData()

### ISSUE THREAD

**Issue by Khysh** [AntonBrock/kwik#1]
Вот [вопрос](https://ru.stackoverflow.com/questions/1095023/%d0%9d%d0%b5-%d1%81%d1%80%d0%b0%d0%b1%d0%b0%d1%82%d1%8b%d0%b2%d0%b0%d0%b5%d1%82-datasource-%d0%bf%d1%80%d0%b8-collectionview-reloaddata/1102592#1102592) на SO

**Comment by Khysh** [comment]
Добавил PR на исправление

**Comment by AntonBrock** [comment]
@Khysh Огромное спасибо за помощь! В этом действительно была проблема! Как жаль, что не вижу еще такие траблы( Но буду стремиться к изучению, чтобы в будущем, возможно, помочь такому же новичку, как я!
